#!/usr/bin/env bash
export TERM='xterm-256color';

if tput setaf 1 &> /dev/null; then
	tput sgr0; # reset colors
	bold=$(tput bold);
	reset=$(tput sgr0);
	black=$(tput setaf 0);
	blue=$(tput setaf 69);
	cyan=$(tput setaf 87);
	green=$(tput setaf 83);
	orange=$(tput setaf 202);
	purple=$(tput setaf 171);
	red=$(tput setaf 196);
	violet=$(tput setaf 177);
	white=$(tput setaf 250);
	yellow=$(tput setaf 226);
else
	bold='';
	reset="\e[0m";
	black="\e[1;30m";
	blue="\e[1;34m";
	cyan="\e[1;36m";
	green="\e[1;32m";
	orange="\e[1;33m";
	purple="\e[1;35m";
	red="\e[1;31m";
	violet="\e[1;35m";
	white="\e[1;37m";
	yellow="\e[1;33m";
fi;

# Highlight the user name when logged in as root.
if [[ "${USER}" == "root" ]]; then
	userStyle="${red}";
else
	userStyle="${bold}${red}";
fi;

# Highlight the hostname when connected via SSH.
if [[ "${SSH_TTY}" ]]; then
	hostStyle="${bold}${blue}";
else
	hostStyle="${red}";
fi;

# Set the terminal title and prompt.
PS1="\[\033]0;\W\007\]"; # working directory base name
PS1+="\[${bold}\]\n"; # newline
PS1+="\[${userStyle}\]Ubuntu"; # localhost
PS1+="\[${white}\] on ";
PS1+="\[${hostStyle}\]C9Z390"; # host
PS1+="\[${white}\] \u in ";
PS1+="\[${green}\]\w"; # working directory full path
PS1+="\n";
PS1+="\[${white}\]\$ \[${reset}\]"; # `$` (and reset color)
export PS1;

PS2="\[${yellow}\]→ \[${reset}\]";
export PS2;
